
version: 2
sources:
  - name: datafeed_shared_schema
    database: "{{('dbt_db')}}"
    schema: STAGING_LAYER

    tables:
      - name: STG_EMPLOYEES
      - name: STG_ORDERS
        columns:
          - name: id
            tests:
              - unique
              - not_null
      - name: Supplies
      - name: Raw_Products
